add SkipCertificateCheck parameter
techservicesillinois/SecOps-Powershell-Splunk pull request #13
Opened 2023-05-01 21:27 UTC by mabaumgartner

## [1.1.3] - 2023-05-01

### Changed

- Send-SplunkHECEvent.ps1 now has a parameter `SkipCertificateCheck` to allow for connections to dev environments with self-signed certificates on the HEC endpoint.

2023-05-01 21:49 UTC, mpitcel approved these changes

2023-05-02 15:22 UTC, baristaTam requested changes
Since you've added a new parameter, could you please regenerate the Markdown Help as well? Make sure the module is reloaded with your changes in your local environment (Remove then re-import module), delete the old markdown files in the help folder, then using PlatyPS run New-MarkdownHelp -Outputfolder ./help -Module UofISplunkCloud

2023-05-02 19:14 UTC, baristaTam approved these changes

2023-05-02 19:20 UTC, mpitcel approved these changes

2023-05-02 21:15 UTC, merged